Meta: Fix uutils coreutils `du` detection
As uutils coreutils (a Rust GNU coreutils reimplementation)
`du --help` doesn't include any information where it comes from,
but `du -V` does:
```
[starterx4@doadgrz ~]$ du -V
du (uutils coreutils) 0.1.0
```

We have to use it then to detect uutils correctly as
the BSD `-A` argument fails (uutils is not BSD-compatible):
```
error: unexpected argument '-A' found

  tip: to pass '-A' as a value, use '-- -A'

Usage: du [OPTION]... [FILE]...
       du [OPTION]... --files0-from=F
error: unexpected argument '-A' found

  tip: to pass '-A' as a value, use '-- -A'

Usage: du [OPTION]... [FILE]...
       du [OPTION]... --files0-from=F
```

Also we have to use `--apparent-size`
due to a bug with `-b` (#26121)